### ISSUE TITLE
Hide PM2's Keymetrics ad, it's confusing people

### ISSUE THREAD

**Issue by ide** [exponent/exp#10]
PM2 prints out an ad for the paid Keymetrics service, which isn't useful to any of our users. It's confusing since PM2 is an implementation detail to them, and `exp` runs locally, not on a server that needs to be monitored anyway.

Creating a marker file looks like the best way to hide the banner: https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L69.

**Comment by dikaiosune** [comment]
I'm no longer seeing the ad on this fresh machine. Let me know if I just missed it somehow though.
