### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by OFranke** [exponent/exp#27]
Hi,
I am trying to build my iOS app via exp build:ios

Heres what I do:

C:\TIB-IDE\App\io.booni.app>exp build:ios
[exp] Checking if current build exists...
[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...
[exp] Validating Apple credentials...
[exp] Credentials valid.

? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? true

[exp] Generating distribution certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch distribution certificate: Unable to add new certificate to your account (maximum number reached). Please delete one of your certificates or upload an existing one.
Error: Unable to fetch distribution certificate: Unable to add new certificate to your account (maximum number reached). Please delete one of your certificates or upload an existing one.

The Distribution Certificate is actually created and I am able to download it from Apple.
Anyway,,  deleted all the certificates I had on my Apple Dev account. Basically my account is completely clean now. I also tried with different Apple Dev Accounts (Enterprise + Normal) but I still face the issue.

Can anyone guide me how to resolve this?

**Comment by OFranke** [comment]
Btw I am using an Company / Organization Entity Type Apple Account if that matters.
Don't know if it would work with a single user Apple Dev account

**Comment by dikaiosune** [comment]
Hi! Sorry it's taken so long to reply here.

A few questions:

1) Is your Apple Developer Program subscription up to date (you can usually see this under the expiration date of the Membership tab)?
2) Have you tried running `exp build:ios -c` after you cleared the certificates?
3) On the Organization account, do you have permissions to create new certificates?

**Comment by OFranke** [comment]
Hi! I'm glad to have you here :)

1. Yes, it will expire on 31th October 2017
2. Yep, I completely cleaned the Apple account. No Certificates, no App IDs and no Provisioning Profiles.
3. I am using the admin account, so I should have that. Actually when the CLI says "[exp] Generating distribution certificate..." it does create the Distribution Certificate on my account.

If possible I could invite you to the Apple Developer Team if that helps. 
Btw I tried it with exp version 0.30.0 and I tried it on both Windows and Mac to be sure this is not a local problem. Both did not work

**Comment by dikaiosune** [comment]
Sorry for the delay, I've been tracking down potentially related issues with the iOS infrastructure. I think they've been resolved, could you try again please?

**Comment by OFranke** [comment]
I just ran npm install -g exp to get the latest update.

Still no luck with this. But the Distribution Certificate is still created in my Apple Account.

Here's what I did:
> We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
> ? What's your Apple ID? XXXX
> ? Password? *XXXX
> ? What is your Apple Team ID (you can find that on this page: https://developer
> .apple.com/account/#/membership)? XXXX
> [exp] Validating Apple credentials...
> [exp] Credentials valid.
> 
> ? Do you already have a distribution certificate you'd like us to use,
> or do you want us to manage your certificates for you? true
> [exp] Generating distribution certificate...
> [exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
> [exp] Unable to fetch distribution certificate: Unable to add new certificate to your account (maximum number reached). Please delete one of your certificates or upload an existing one.

**Comment by dikaiosune** [comment]
@OFranke can you DM me on our slack with the name of your project and your exponent username? I'd like to check the logs for this. I'm `ap` on our community slack: http://slack.getexponent.com/

**Comment by OFranke** [comment]
For anyone else: seems that this is an UTF-8 issue in the certificates name (stupid German umlauts ä,ö,ü).

**Comment by dikaiosune** [comment]
@OFranke just to update you, I finished deploying a fix for this i18n issue. Sorry for the inconvenience! Can you try the build again?

**Comment by dikaiosune** [comment]
Per a slack conversation, this issue was resolved and non-ASCII cert characters should now be supported.

**Comment by AbeHerbert** [comment]
I'm still finding that there is an issue with build:ios

**Comment by ide** [comment]
@AbeHerbert Can you provide the error log and verify that it's the same output as the original post's?

**Comment by flo-pereira** [comment]
same for me:

`
$ exp build:ios
[exp] Making sure project is set up correctly...
-[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? #####
? Password? *****
? What is your Apple Team ID (you can find that on this page: https://developer.apple.com/account/#/membership)? #####
[exp] Validating Apple credentials...
[exp] Credentials valid.

? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? true
[exp] Generating distribution certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch distribution certificate: Unable to add new certificate to your account (maximum number reached). Please delete one of your certificates or upload an existing one.`

**Comment by digitalmaster** [comment]
I'm also seeing this same error.. it worked fine yesterday. 
```
$ exp build:ios -c
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? XXXXXXX@XXXXX.XXX
? Password? **********
? What is your Apple Team ID (you can find that on this page: https://develop
er.apple.com/account/#/membership)? XXXXXXX..
[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID XXXXXXX-XXX-XX.., message: Internal error occurred. Please try again in a few minutes or contact support.
```

**Comment by nicholasdickey** [comment]
I see this error too. This is my first attempt at ios build:
sudo exp build:ios -c
[exp] Making sure project is set up correctly...
-[exp] Warning: 'react-native' peer depencency missing. Run `npm ls` in /home/nick/root/qwiket to see full warning.
[exp] 
[exp] If there is an issue running your project, please run `npm install` in /home/nick/root/qwiket and restart.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? ***@***.com
? Password? ****************
? What is your Apple Team ID (you can find that on this page: https://developer.
apple.com/account/#/membership)? XXXXXXXX
[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 63412a00-6afb-11e7-9e98-a5ae72fdf697, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by dikaiosune** [comment]
@nicholasdickey hi! Sorry about that. One of our builders ran out of disk space. It's been cleared, and I'm working on a fix for the bug that caused it to fill up. Can you try again?

@digitalmaster can you paste your request ID? It's easiest to find in the logs if we have that.

**Comment by digitalmaster** [comment]
@dikaiosune just tried it again and it's working now.. no validation error so no ID this time.. If it happens again i'll post with ID.. Thanks

**Comment by digitalmaster** [comment]
@dikaiosune Woops.. happening again although slightly different error.. Instead of "unable to validate" -> "unable to fetch":

```
[exp] Generating distribution certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch distribution certificate. Request ID 4f54fd70-6b5d-11e7-9988-d3c1139052b1, message: Unable to add new certificate to your account (maximum number reached). Please delete one of your certificates or upload an existing one.
```

**Comment by JoeRoddy** [comment]
For other dummies like me, you can revoke your certificates here:
https://developer.apple.com/account/ios/certificate/

**Comment by jackrobson** [comment]
Tried exp build:ios -c

For the following output:
`We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? EMAILADDRESS@HIDDEN.com
? Password? ***************
? What is your Apple Team ID (you can find that on this page: https://developer.
apple.com/account/#/membership)? MYIDWASHERE
[exp] Validating Apple credentials...
[exp] Credentials valid.

? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? true
[exp] Generating distribution certificate...
[exp] Distribution certificate setup complete.
[exp] Validating app id...
? Do you already have a push notification certificate you'd like us to use,
or do you want us to manage your push certificates for you? true
[exp] Fetching a new push certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch push certificate. Request ID e52e6e10-804a-11e7-991c-5d0e984f835b, message: Internal error occurred. Please try again in a few minutes or contact support.`

Also tried following link JoeRuddy provided and revoke all certificates just to encounter same problem.

**Comment by jackrobson** [comment]
Update: 
I think my problem was due to having too many different defunct App IDs found at https://developer.apple.com/account/ios/identifier/bundle

Problem solved! :)

**Comment by franckmaurin** [comment]
Same error here. I deleted all my certificates and this again.
```
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 250e29d0-8753-11e7-b518-8b3e547ff520, message: Internal error occurred. Please try again in a few minutes or contact support.
```

**Comment by gopidon** [comment]
Hey I am getting this error:

Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID db9e1d30-8b4b-11e7-8d18-2d1d703ec004, message: Internal error occurred. Please try again in a few minutes or contact support.

Any pointers?

**Comment by nicholasdickey** [comment]
same here. Build is not working error validating credentials.

**Comment by gopidon** [comment]
Okay, some progress.. the build is getting submitted but no build ID generated.

[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build.

When requesting support, please provide this build ID:

**undefined**

**Comment by gopidon** [comment]
its working now I guess

**Comment by jakeols** [comment]
Hey everyone - having this issue as well. I tried waiting + revoking any certificates in my account, etc. , request ID is aa1bb590-926e-11e7-9306-699932aad8e4 .

**Comment by dikaiosune** [comment]
@jakeols it looks like this might have been a temporary issue, but we're seeing `Could not find app with bundle id 'com.jakeols.status' ` from fastlane.

**Comment by EJohnF** [comment]
hi! 
The same problem as above
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 91781c10-927b-11e7-936b-9d8f349dfd92, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by dikaiosune** [comment]
@EJohnF we don't have an integration with bitrise, sorry. It looks like your error was from a temporary outage on apple's servers.

**Comment by jakeols** [comment]
@dikaiosune Thanks for the reply- I'm still experiencing this issue but am seeing the certs generated through my developer console. Is there anything else that I should be doing?

**Comment by dikaiosune** [comment]
@jakeols are you sure that bundle identifier is available?

**Comment by jakeols** [comment]
@dikaiosune That was it actually- thanks! Didn't realize that identifier was used.

**Comment by jiwokim** [comment]
Hi there. 
I have a same ios build error
Build ID: 511ca3ab-27f8-4ffb-a858-e4abcffbbdf7

[exp] Checking if current build exists...
[exp] ============
[exp] Build Status
[exp] ============
[exp] iOS: There was an error with this build.

Can you check my error?

**Comment by aravandi** [comment]
I'm also seeing this error:
[exp] Build ID: 0770c4f7-7492-4c0e-85ac-5764653fb4b7

[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build.

Could you check it for me too!

**Comment by fabiocastrodev** [comment]
We need your Apple ID/password to manage certificates and provisioning profiles
from your Apple Developer account.
? What's your Apple ID? xxxxxxxx
? Password? ********
? What is your Apple Team ID (you can find that on this page: https://developer
.apple.com/account/#/membership)? Personal Team
[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and t
ry again.
[exp] Unable to validate credentials. Request ID 19785750-b406-11e7-9fca-971d4d9
2d8d8, message: Internal error occurred. Please try again in a few minutes or co
ntact support.

**Comment by benben198805** [comment]
Hey there 
I have same issue. And already running with -c + revoking any certificates in my account. 
request ID is 0e7c3560-b41a-11e7-be22-fde1a836be2f.

Full version:
Unable to validate credentials. Request ID 0e7c3560-b41a-11e7-be22-fde1a836be2f, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by gopidon** [comment]
Its erring out again. Only while building for ios. Android goes through fine.

Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 87bea480-b587-11e7-bbee-cf66195a3c9a, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by gopidon** [comment]
Hi, any update on this? I am still unable to generate the .ipa

**Comment by jakeols** [comment]
Having another issue - when going to update my build: Receiving this output. No request ID or anything. 

```
[exp] Checking if current build exists...
[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] API Response Error: Not authorized.
```

**Comment by lhp--** [comment]
same here !!! 

> "Unable to fetch push certificate. Request ID 213e9eb0-bf8f-11e7-8d94-af5be10d03e1, message: Internal error occurred. Please try again in a few minutes or contact support."

**Comment by ricardoshimoda** [comment]
Is there a way to clear apple credentials manually? I've been trying to run
exp build:ios -c 

And it only repeats the same message - that the credentials are invalid and that I should try to use the option '-c'- as if "cleaning" the credentials isn't really working..

**Comment by brentvatne** [comment]
@ricardoshimoda - if it says that then it's quite possible that the credentials you are supplying are actually invalid. another alternative is that your account requires two-factor authentication, which is not currently supported with the Expo builder (we are working on it, should be available shortly)

**Comment by organicnz** [comment]
Can anyone help? I'm still getting this error.

```
Organic:cleanme organic$ exp build:ios
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...
[exp] Validating Apple credentials...
[exp] Credentials valid.
[exp] Validating distribution certificate...
[exp] Validating app id...
? Do you already have a push notification certificate you'd like us to use,
or do you want us to manage your push certificates for you? true
[exp] Fetching a new push certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch push certificate. Request ID f9f8e370-c2d5-11e7-b698-797806970be6, message: Internal error occurred. Please try again in a few minutes or contact support.
```

**Comment by brentvatne** [comment]
@organicnz - make sure you don't have the maximum number of push certificates on itunes connect

**Comment by organicnz** [comment]
@brentvatne - I've already deleted them yesterday and got only created by Expo.

**Comment by organicnz** [comment]
I've just renamed the Bundle ID in app.json and it looks working now.

```
organic$ exp build:ios -c
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? tamerlanium@gmail.com
? Password? ********
? What is your Apple Team ID (you can find that on this page: https://developer.apple.com/account/#/membership)? DCKV******
[exp] Validating Apple credentials...
[exp] Credentials valid.

? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? true
[exp] Generating distribution certificate...
[exp] Distribution certificate setup complete.
[exp] Validating app id...
? Do you already have a push notification certificate you'd like us to use,
or do you want us to manage your push certificates for you? true
[exp] Fetching a new push certificate...
[exp] Push certificate setup complete.
[exp] Starting build process...
[exp] Publishing...
[exp] Building iOS bundle
[exp] Building Android bundle
[exp] Analyzing assets
[exp] Uploading assets
[exp] No assets changed, skipped.
[exp] Uploading JavaScript bundles
[exp] Published
[exp] Your URL is

https://exp.host/@organic/******

[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: 2fc0e3ee-9391-483a-ad0d-96a23f13ebd4
[exp] Run `exp build:status` to monitor it.
```

**Comment by TunedMidja** [comment]
I'm getting this now (using the -c option and a P12 certificate):
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 25aa0200-cb6a-11e7-b70f-474aca5803bb, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by artpi** [comment]
```
artpi~/GIT/czykupie(master🔥 ) 😃 🚀  EXPO_DEBUG=true exp build:ios --local-auth 
[exp] Making sure project is set up correctly...
|[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
  ....
[exp] Validating Credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] undefined
[exp] undefined
```

My account is valid, I cleaned out provisioning profiles and have 2factor enabled.
Now that I disabled 2fa works fine.

I hope it will start working with 2fa soon!
Otherwise - spectacular work!

**Comment by dikaiosune** [comment]
@artpi you can try 2FA support using the `--local-auth` flag.

**Comment by dikaiosune** [comment]
Actually, going to lock this issue now since we don't monitor this repo closely. If you're having issues with standalone builds, please post to the [forums](https://forums.expo.io). Thanks!
