### ISSUE TITLE
Allow mono-repo workflow using getProjectRoots in config file

### ISSUE THREAD

**Issue by pillowsoft** [exponent/exp#29]
We have react-native set up to develop as a mono-repo, using the config file (rn-fli.config.js) feature of the RN packager. We use the getProjectRoots part of the config like this:
```
	getProjectRoots() {
		const projectRoots = [
			projectDir,
			buildConfig.paths.packages,
			buildConfig.paths.node_modules,
		];
		return projectRoots;
	},
```
this works great with RN and allows us to have a single shared node_modules folder and a single folder containing all our shared packages (i.e shared modules and multiple apps sharing those modules).

I attempted to get this to work with Exponent and alas, we run into the first issue. Exponent always checks to ensure that any app contains a node_modules folder and react-native within it. Since we don't have those in the app's folder it (the packager) fails to run. It appears the exp CLI code has a flag (alas not exposed to the CLI/app) to force it to not check for these. 

Could this be added as a CLI arg and/or and exp.json field? Another possibility would be to do the same validation, but search for node_modules in the project roots of the exp.json file, if not found in the app folder. The fix would also need to be made in xdl.

Note: if I change the code in exp and xdl to skip the validation tests, then it does start running, to where I see this:
```
[exp] pm2 managed process exists
[exp] Starting exp-serve process under pm2
[exp] Waiting for packager, etc. to start
```

but it stays at "Waiting for packager, etc. to start", so apparently removing the validation is not the only fixe to allow this useful workflow.

**Comment by dikaiosune** [comment]
Hi! I think this should already work. See https://docs.getexponent.com/versions/v12.0.0/guides/configuration.html#ignoreNodeModulesValidation and https://docs.getexponent.com/versions/v12.0.0/guides/configuration.html#nodeModulesPath. You can also specify your rn-cli.config.js in exp.json:

```
{
  name: "foo",
  ...
  nodeModulesPath: "/path/to/directory_containing_node_modules",
  packagerOpts: {
    config: "rn-cli.config.js"
  }
}
```

Let us know if that addresses your needs?

**Comment by pillowsoft** [comment]
Sorry I missed those in the documentation. You must have read my mind. Thanks!  I just tried it and it gets me one step further. I.e. it gets me past the issues with the validation and then I get here:

```
[exp] Making sure project is set up correctly...
/[exp] Warning: Can't find react-native in package.json dependencies
[exp] Your project looks good!
[exp] pm2 managed process exists
[exp] Starting exp-serve process under pm2
[exp] Waiting for packager, etc. to start
-
```
 and then it just sits waiting for the packager to start.  If I run the exp log command, there are no errors.  Suggestions?

**Comment by dikaiosune** [comment]
Can you paste your package.json dependencies? I'm a little worried by `Warning: Can't find react-native in package.json dependencies`.

**Comment by pillowsoft** [comment]
My package.json did not have dependencies listed, since they're all in the mono-repo's node folder and the package.json for it. I just updated the package.json to this:

```
{
	"name": "workhere-rn-app",
	"version": "0.0.1",
	"private": true,
	"main": "index.ios.js",
	"dependencies": {
		"@exponent/ex-navigation": "^2.7.1",
		"@exponent/samples": "^1.0.2",
		"@exponent/vector-icons": "^4.0.0",
		"react": "^15.4.1",
		"react-native": "git+https://github.com/exponentjs/react-native#sdk-12.0.0",
		"styled-components": "^1.3.1"
	}
}
```

...alas, no change, other than getting rid of the warning about react-native.

**Comment by dikaiosune** [comment]
Interesting. Exponent's tools generally look for an `index.js` file, rather than platform-specific entry points. Can you try renaming your iOS entry point to just `index.js`?

**Comment by pillowsoft** [comment]
I tried that and no change. I figured the entry point in package.json was ignored when specified in the exp.json, like here:

```

{
	"name": "workhereApp",
	"description": "No description",
	"slug": "workhereApp",
	"privacy": "public",
	"sdkVersion": "12.0.0",
	"version": "1.0.0",
	"orientation": "portrait",
	"primaryColor": "#cccccc",
	"iconUrl": "https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png",
	"notification": {
		"iconUrl": "https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon-blue-circle.png",
		"color": "#000000"
	},
	"loading": {
		"iconUrl": "https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png",
		"hideExponentText": false
	},
	"entryPoint": "./index.ios.js",
	"rnCliPath": "./rn-cli.config.js",
	"ignoreNodeModulesValidation": true,
	"nodeModulesPath": "/Users/bpillow/Documents/Git/workhere-redux/node_modules",
	"ios": {
		"supportsTablet": true
	}
}
```

**Comment by pillowsoft** [comment]
I'm going to try to make a smaller example and put it in a repo for you to look at.

**Comment by pillowsoft** [comment]
Git repo here: https://github.com/pillowsoft/exp-nodemodules-setting-test, to demo hang on wait for packager. Seems to have to do with the nodeModulesPath setting.

**Comment by pillowsoft** [comment]
Alas, it turns out this was my mistake :-( My apologies!  The exp.json had rnCLiPath point to the rnCliConfigPath, i.e. not the packager path.  With that fixed, the packager no longer "hangs". It must not have been hanging before, but wherever you start the packager, it couldn't find it and did not report an error. You may want to add an error for this for folks like me who give it the wrong path. 

Now all is working, but something else is causing the app once launched to crash. Off to figure that out. Once I get it working, I'll put up a medium blog post on this mono-repo workflow.

Thanks!

**Comment by dikaiosune** [comment]
Hi! Sorry I hadn't had a chance to try to reproduce this, but I'm glad that you were able to sort things out! I'll make a note that we aren't reporting the error here very well, thanks for the heads up!

**Comment by pillowsoft** [comment]
No worries!  There is still an issue which seems broken with node_module resolution when **"nodeModulesPath"** is set.  The simplest way to demo is to create a new exponent project. Next, move the node_modules folder up one folder (i.e. the folder above the project).  Now add these lines to your exp.json:

```
	"rnCliPath": "../node_modules/react-native/local-cli/cli.js",
	"ignoreNodeModulesValidation": true,
	"nodeModulesPath": "../node_modules",
```

per the documentation, this should work (?). The packager does run, but I get a red screen error that it cannot find the module "exponent" in...and then it lists the correct absolute path to the node_modules folder above the project.

The odd thing is that I saw this same pattern in the new react-navigation repo, here:

react-navigation-master/examples/NavigationPlayground/exp.json 

Alas, I could not get it to work either. Seems there's a bug or I have something munged.  Does the simple test above (with node_modules up one folder) work for you?

Thanks!

**Comment by pillowsoft** [comment]
FYI, I also tried:

```
"nodeModulesPath": "../node_modules"
```
as well as:

```
"nodeModulesPath": ".."
```

Both have the same effect.

**Comment by joshyhargreaves** [comment]
Just a word of warning to those wishing to set the RN Packager routes through `getProjectRoutes` in a a config file such as `rn-cli.config.js`, the routes returned by `getProjectRoutes` are not respected by the packager, it would seem, unless you explicitly set the `packagerOpts` option, `projectRoots` to an empty string.
So like so:

```
packagerOpts: {
  config: "rn-cli.config.js",
  projectRoots: ""
}
```
That is a bit of a curveball! ¯\\\_(ツ)\_/¯
