### ISSUE TITLE
Error Validating Apple Credentials

### ISSUE THREAD

**Issue by OFranke** [exponent/exp#31]
Hi,

I just faced an issue building the iOS release .ipa file.

I've tried it with version 0.30.1 and also the latest version on Windows as well as on MacOS. Here's the log:

C:\TIB-IDE\App\my.cool.app>exp build:ios -c
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? ***************
? Password? ***********
? What is your Apple Team ID (you can find that on this page: https://developer
.apple.com/account/#/membership)? *********
[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials: Internal error occurred. Please try again in a few minutes or contact support.

I've made sure that my credentials are absolutely valid. Also I have not changed anything (no updates of NPM, exp, anything else). A few days ago everything worked fine. Does anybody know whats happening?

Building Android works fine btw!

Best regards,
Oliver

**Comment by dikaiosune** [comment]
Hi! We had an issue with the networking to our iOS build machines this morning. I've just brought that service back online, and everything appears to be functioning. Can you give it another try?

Also, just a note that you should only need to build the IPA once for each "version" of your `exp.json` file. The newest version of your JavaScript will be pushed out to the client, unless you make changes to the `exp.json` manifest (updating the sdk version, changing the bundle identifier, etc).

**Comment by OFranke** [comment]
Hi Adam,
it all seems to work fine again!

Thanks for the info. I've had to do some changes in exp.json, thats why I had to create a new build.

Thanks for your help! :-)

**Comment by ph3b** [comment]
Hi! I have been struggling with this for the last two days as well. Getting the exact same error with 2FA disabled on my Apple ID.

**Comment by dikaiosune** [comment]
@ph3b I'm going to be online intermittently for the next couple of days, but please get in touch with me on our [community slack](https://slack.expo.io) (my username it `ap` there) so I can find out more about your failed build. We're working on improving this system but for now I need to manually check logs for your build to see what failed.

**Comment by andrewkmin** [comment]
Bump. running into the same issue now.
