### ISSUE TITLE
Unable to validate credentials: Internal error occurred

### ISSUE THREAD

**Issue by karinpang** [exponent/exp#34]
Hi,

I want to build standalone apps and android is ok, but fail in building iOS. I am using version 32.3.0, and here is the log:

[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? XXXXXXXXXX
? Password? ********
? What is your Apple Team ID (you can find that on this page: https://developer.apple.com/account/#/membership)? XXXXXXXXXX
[exp] Validating Apple credentials...
[exp] Credentials valid.

? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? false
? Path to P12 file: XXXXXXXXXX.p12
? Certificate P12 password (empty is OK): ********
[exp] Validating distribution certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials: Internal error occurred. Please try again in a few minutes or contact support.

Since it only reply with "Internal error occurred", so I am confused and not sure what the problem is. Is there any method or logs that I can trace for this error? Thanks for help.

**Comment by karinpang** [comment]
Hi,

I remove an old certificate and choose exp to manage certificates, and finally build successfully:

```
? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? true
[exp] Generating distribution certificate...
[exp] Distribution certificate setup complete.
[exp] Validating app id...
? Do you already have a push notification certificate you'd like us to use,
or do you want us to manage your push certificates for you? true
[exp] Fetching a new push certificate...
[exp] Push certificate setup complete.
[exp] Starting build process...
[exp] Publishing...
[exp] Published
[exp] Your URL is

https://exp.host/XXXXXXX

[exp] Building...
[exp] Build successfully started, it may take a few minutes to complete. Run "exp build:status" to monitor it.
```


But after that when I check back by 'exp build:status', the following displayed:

```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build. Please try again.
```

I've tested the apps through exponent client and do not find any errors. So I am not sure what's going wrong. Is there any method to check what's the problem? Since there are no further details to find out the problem.

Also, when I want to try to create a simple apps to test and run exp start, the following error shown:

```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
Error: connect EPERM //./pipe/rpc.sock
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

**Comment by dikaiosune** [comment]
Hi! Sorry about the delay in responding to this. Could you paste the contents of your package.json and exp.json files? If you'd prefer, you could also DM them to me on our community slack (slack.getexponent.com to register) -- my username there is `ap`.

**Comment by karinpang** [comment]
Thanks for the reply. I may send you the file in next 2 days.

**Comment by karinpang** [comment]
The required files sent through slack, please check and see if any problem, thanks.

**Comment by ranahyder87** [comment]
Please post here if you find the solution, Thanks.

**Comment by gardner** [comment]
This is blocking.

```
[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID b4657860-9f48-11e7-baf3-ad8722db9376, message: Internal error occurred. Please try again in a few minutes or contact support.
```

Is there any way to get more information about what is happening?

```
$ exp build:ios -c
[exp] Making sure project is set up correctly...
\[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...

We need your Apple ID/password to manage certificates and provisioning profiles from your Apple Developer account.
? What's your Apple ID? REDACTED@gmail.com
? Password? ******************
? What is your Apple Team ID (you can find that on this page: https://developer.apple.com/account/#/membership)? REDACTED
[exp] Validating Apple credentials...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID ffc614d0-9f49-11e7-b308-1f857236c91e, message: Internal error occurred. Please try again in a few minutes or contact support.
```

Thanks!

**Comment by ranahyder87** [comment]
I faced this problem for 2 days. Then suddenly it works without any change or hurdle.
I read from somewhere that they got server space problem that's why "internal error" happens. Don't know about much.

**Comment by gardner** [comment]
Free, unsupported, and non-deterministic can be difficult to rely on for real world use.

I appreciate that the team is not making money off expo and that it is free. Can we host our own build service? Is the recommended way to do this to eject?

**Comment by dikaiosune** [comment]
@gardner, sorry to hear you're having problems. We don't actively monitor this repo's issues anymore (see issue template), but if you paste your info on the forums I can make sure someone helps you tomorrow morning.

In the Readme of https://github.com/expo/expo there are some instructions for running standalone builds yourself without depending on our service.
