### ISSUE TITLE
`npm test` throws "jest: not found" on example "tabs" project

### ISSUE THREAD

**Issue by yurivyatkin** [exponent/exp#35]
When I create a new project with either XDE "New Project"/"Tab Navigation" or with `exp init` choosing tabs option, running `npm test` fails with the following output:
```
$ npm test
> test-exp-project@0.0.0 test /home/yuri/Work/test-exp-project
> jest

sh: 1: jest: not found
npm ERR! Test failed.  See above for more details.
```
An inspection shows that jest is actually present in the dependency tree:
```
$ npm ls jest
test-exp-project@0.0.0 /home/yuri/Work/test-exp-project
└─┬ jest-exponent@0.2.1
  └── jest@18.1.0 
```
I work on Ubuntu 16.04, Node v7.4.0, npm 4.0.5, exp 33.0.0, xde-2.15.0-x86_64

Everything else seems to be working fine (e.g. `exp start`, `exp android` etc).

I am able to get jest up and running again with first uninstalling `npm uninstall jest-exponent -D` and then installing it back `npm install jest-exponent -D`.

Cloning https://github.com/exponent/new-project-template does not produce this issue.

**Comment by pangeacake** [comment]
Seems like jest needs to be installed globally for the shell command to be usable.

**Comment by yurivyatkin** [comment]
@pangeacake nope

**Comment by dikaiosune** [comment]
@pangeacake the template projects should work out of the box.

@yurivyatkin thanks for the report, I'll look at this today.

**Comment by dikaiosune** [comment]
@yurivyatkin a fix for this is releasing in new template projects sometime today. The short version is that we were tarring the templates after they were installed with `--no-bin-links` to prevent broken symlinks after unpacking. This obviously prevented the jest binary from being available for `npm test`. We've updated the package.json to run the jest binary directly.

**Comment by laurent22** [comment]
I had the same problem and solved it with installing jest with sudo: `sudo npm install --save-dev jest`
It's possible it's some config problem with my npm setup, but anyway it works now.
