### ISSUE TITLE
[exp build:ios] Error parsing JSON file: /Users/Julian/.expo/state.json

### ISSUE THREAD

**Issue by JulianKingman** [exponent/exp#40]
I get this error when I try to build for ios: ` Error parsing JSON file: /Users/Julian/.expo/state.json`

Ideas?

**Comment by ide** [comment]
Can you email your state.json file to support@expo.io so we can have a look at it? (There's an account access token stored in it so please send it to us over a private channel.)

**Comment by JulianKingman** [comment]
Sent.

**Comment by JulianKingman** [comment]
Hm, no error anymore. Hope it helps anyway?

**Comment by ide** [comment]
Thanks for sending it. Your state.json file looks OK to me (i.e. it's valid JSON) and this error shouldn't happen so we're looking at adding more error checking and logging in places where exp/XDE access state.json. In the meantime if you run into this issue, you can safely delete `~/.expo/state.json` and you'll have to log in again.

**Comment by JulianKingman** [comment]
Good tip, thanks!

**Comment by gmp26** [comment]
It may be a coincidence, but I see this error after saving local state in the IOS simulator. (I'm using glittershark.core-async-storage set-item from cljs).
