### ISSUE TITLE
Unsolvable EMFILE: too many open files, open problem

### ISSUE THREAD

**Issue by ccheever** [exponent/exp#5]
When trying to run `exp` on my sister's almost new MacBook Pro 13", I couldn't get `exp` to work because it would always give this error:

```
Error: EMFILE: too many open files, open '/Users/marycheever/.babel.json'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:549:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1155:15)
    at process.save (/Users/marycheever/projects/exp/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process.exit (node.js:733:17)
    at process.<anonymous> (/Users/marycheever/projects/exp/node_modules/react-native/packager/packager.js:156:11)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
```

Some notes: I tried both iojs-v2.3.4 and iojs-v2.4.0 and they both yielded this result.

I set the ulimit very high which is what commonly seems to solve this problem, but it did not improve things.

```
Marys-MacBook-Pro:exponent-host marycheever$ ulimit
unlimited
Marys-MacBook-Pro:exponent-host marycheever$ ulimit -n
65536
Marys-MacBook-Pro:exponent-host marycheever$
```

I tried various methods of changing to ulimit to make sure it wasn't just affecting my shell and subshells and was indeed propagating to the packager.

Running `exgulper` worked without a problem, so that was surprising. The version of react-native running packager in exp is 0.8.0. The version of react-native used in Exponent/exgulper is 0.8.0 as well.

Even when trying this on a trivial project that is just one file with no node_module dependencies, the problem still occurred. Maybe it is watching too many files under exp?

Or possibly the error message is wrong and actually should be surfacing something else?

In any case, more of an argument for the cloud packager I suppose.

**Comment by ide** [comment]
FD limits on OS X are confusing... IIRC there are three settings you need to change (ulimit being one of them). My conclusion was that it's untenable to ask everyone to increase their limits.

Maybe we could use graceful-fs. Not sure if it handles this specific case but is worth trying.

**Comment by ccheever** [comment]
Unfortunately in this case it seems like graceful-fs was already in use
from the stack trace. I'll try to borrow Mary's computer again to
investigate further since the issue doesn't appear on my own machine.

**Comment by gaearon** [comment]
I also have this problem trying to run `react-native-webpack-server` examples.

```
Error: EMFILE: too many open files, open '/Users/dan/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1152:15)
    at process.save (/Users/dan/p/react-native-webpack-server/Examples/BabelES6/node_modules/react-native/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process.exit (node.js:731:17)
    at process.<anonymous> (/Users/dan/p/react-native-webpack-server/Examples/BabelES6/node_modules/react-native/packager/packager.js:151:11)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
```

**Comment by gaearon** [comment]
Updating Node to 4.0 fixed this for me.

**Comment by ide** [comment]
@gaearon Try installing Watchman (or restarting it, if you already have it installed). That seemed to fix the EMFILE errors we encountered. I haven't tested without Watchman on Node 4.0 but did have the EMFILE issue on io.js 3.3, so I am a little surprised that upgrading Node fixed it. Charlie also made progress using Chokidar in the packager and that seems to have worked too.

**Comment by gaearon** [comment]
I didn't know Watchman was a thing. Does it make watcher faster?

**Comment by ide** [comment]
I'm not sure about speed, though I expect it to be usually as fast or faster than the Node file watcher because Watchman runs as a daemon. Also Watchman does a better job of watching a large number of files and FB uses it to watch their PHP+JS source tree so it certainly scales.

**Comment by gaearon** [comment]
Confirming installing Watchman also fixed the issue on Node 2.

**Comment by dikaiosune** [comment]
This issue is rather old now, and I haven't seen anyone report this error in some time. Closing, but if we can repro please reopen.

**Comment by ablankenship10** [comment]
I am having this issue now with the latest XDE, react-native, and nodejs.

Any reason the files are not closed after opening?
